<?php

return [
    'NAME',
    'SHORT_NAME',
    'OPF',
    'EDRPOU',
    'ADDRESS',
    'STAN',
    'FOUNDING_DOCUMENT_NUM',
    'SUPERIOR_MANAGEMENT',
    'AUTHORIZED_CAPITAL',
    'STATUTE',
    'REGISTRATION',
    'MANAGING_PAPER',
    'TERMINATED_INFO',
    'TERMINATION_CANCEL_INFO',
    'CONTACTS',
    'VP_DATES',
    'CURRENT_AUTHORITY',
];
