<?php

return [
    'SUBJECTS',
    'FOUNDERS',
    'SIGNERS',
    'TERMINATION_STARTED_INFO',
    'BANKRUPTCY_READJUSTMENT_INFO',
    'EXECUTIVE_POWER',
    'ACTIVITY_KINDS',
    'EXCHANGE_DATA',
    'PREDECESSORS',
    'ASSIGNEES',
    'BRANCHES',
    'BRANCHES_ACTIVITY_KINDS',
    'BRANCHES_EXCHANGE_DATA',
];
