
CREATE TABLE `BANKRUPTCY_READJUSTMENT_INFO` (
  `ID` bigint(20),
  `OP_DATE` varchar(10),
  `REASON` varchar(100),
  `SBJ_STATE` varchar(50),
  `BANKRUPTCY_READJUSTMENT_HEAD_NAME` varchar(400)
) ENGINE=InnoDB DEFAULT CHARSET=cp1251
